# Generated by Django 2.2.2 on 2019-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0002_filmsbase_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsbase',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
