# Generated by Django 2.2.2 on 2019-11-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0003_auto_20190628_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsbase',
            name='films',
            field=models.CharField(max_length=100),
        ),
    ]
