# Generated by Django 2.2.2 on 2019-11-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premieres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premierlist',
            name='films',
            field=models.CharField(max_length=100),
        ),
    ]
